# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20161001_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 8, 21, 24, 85196, tzinfo=utc)),
        ),
    ]
